
name: 
  V1.Realse---Dev
spring: 
  datasource: 
    url: jdbc:mysql:///world?useSSL=true
    username: '{cipher}AQBj5GhaveOmr20iWIzlw2ti1Av+tUTjushDZZZN15p68UoY/kj2xXcIzC2OT0dCiBiQy+Z8vKER7UemhkCINYdgHJTdMDGKWurr0C+qRKvHJ1auqPaUmxjSFJwpG0uE5SGP2g1VP2TklJflHh2PvTUgWIEMw7198lBJaQvvjk/16xvOFM413BzZA68N0YyThvBLY/YxJ7LCcbXvEZw5uRfHnnMl1LiAq1mW+XfL/8UeoY5eQH8Ppx0ePnZ+I1p7g2igpH35C6SwALWVPZWeTfPzzVAVwTbtcOnw9y58Dm+mMlwrtnTpoZJVTGin99A8j45e2T6oVYh+EYqDdXRKTz8wdIkTgDXJftUGlVRqn5E0L4k9spySZOft6/214vDyVJo='
    password: root
    driver-class-name: com.mysql.jdbc.Driver
